/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.Color;
import java.awt.Graphics2D;
import static java.awt.GridBagConstraints.BOTH;
import java.awt.Image;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JPanel;


/**
 *
 * @author Herie-PC
 */
public final class frmUtama extends javax.swing.JFrame {

    /**
     * Creates new form frmUtama
     */
    private String gambar=null;

    

    public String getGambar() {
        return gambar;
    }

    public void setGambar(String gambar) {
        this.gambar = gambar;
    }
    
    
    public frmUtama() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
        tampilkanLogo("Logo Amikom Baru.png");
        tampilIcon();
        //menu(false, false, false);
    }
    
    public void tampilIcon(){
         mnExit.setIcon(tampilkanIcon("exit.png"));
         mnDosen.setIcon(tampilkanIcon("dosen.png"));
         mnMatkul.setIcon(tampilkanIcon("matkul.jpg"));
         mnJadwal.setIcon(tampilkanIcon("jadwal.png"));
         mnRuang.setIcon(tampilkanIcon("ruang.jpg"));
         mnReservasi.setIcon(tampilkanIcon("reservasi.png"));
         mnDtMatkul.setIcon(tampilkanIcon("dtMatkul.png"));
         mnDtRuang.setIcon(tampilkanIcon("dtRuang.png"));
    }
    
    public Icon tampilkanIcon(String lg) {
        ImageIcon imageIcon = new ImageIcon("src/image/"+lg); // load the image to a imageIcon
        Image image = imageIcon.getImage(); // transform it 
        Image newimg = image.getScaledInstance(19, 19,  java.awt.Image.SCALE_DEFAULT); // scale it the smooth way  
        imageIcon = new ImageIcon(newimg);
        
        return imageIcon;
    }
    
    
    public void menu(boolean a, boolean b){
        mnMaster.setEnabled(a);
        nmReservasi.setEnabled(a);
        mnExit.setEnabled(b);
    }
    
    
    
   public void tampilkanLogo( String lg) {
        String urlGambar = "src/image/"+lg;
        ikon i=new ikon();
        BufferedImage loadImg = ikon.loadImage(urlGambar);
        ImageIcon imageIcon = new ImageIcon(ikon.resize(loadImg,
        lblGambar.getWidth(), lblGambar.getHeight()));
        lblGambar.setIcon(imageIcon);
    }
  

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        dpHome = new javax.swing.JDesktopPane();
        lblGambar = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnMenu = new javax.swing.JMenu();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnExit = new javax.swing.JMenuItem();
        mnMaster = new javax.swing.JMenu();
        mnDosen = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JPopupMenu.Separator();
        mnMatkul = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JPopupMenu.Separator();
        mnRuang = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnDtMatkul = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        mnDtRuang = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        mnJadwal = new javax.swing.JMenuItem();
        nmReservasi = new javax.swing.JMenu();
        mnReservasi = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 0, 153));

        dpHome.setBackground(new java.awt.Color(153, 153, 153));
        dpHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout dpHomeLayout = new javax.swing.GroupLayout(dpHome);
        dpHome.setLayout(dpHomeLayout);
        dpHomeLayout.setHorizontalGroup(
            dpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dpHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(522, Short.MAX_VALUE))
        );
        dpHomeLayout.setVerticalGroup(
            dpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, dpHomeLayout.createSequentialGroup()
                .addContainerGap(376, Short.MAX_VALUE)
                .addComponent(lblGambar, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        dpHome.setLayer(lblGambar, javax.swing.JLayeredPane.DEFAULT_LAYER);

        getContentPane().add(dpHome, java.awt.BorderLayout.CENTER);

        jMenuBar1.setBackground(new java.awt.Color(204, 204, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuBar1.setForeground(new java.awt.Color(204, 204, 0));

        mnMenu.setText("Menu");
        mnMenu.add(jSeparator1);

        mnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_X, java.awt.event.InputEvent.SHIFT_MASK));
        mnExit.setText("Exit");
        mnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnExitActionPerformed(evt);
            }
        });
        mnMenu.add(mnExit);

        jMenuBar1.add(mnMenu);

        mnMaster.setText("Master");

        mnDosen.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.ALT_MASK));
        mnDosen.setText("Dosen");
        mnDosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDosenActionPerformed(evt);
            }
        });
        mnMaster.add(mnDosen);
        mnMaster.add(jSeparator6);

        mnMatkul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.ALT_MASK));
        mnMatkul.setText("Mata Kuliahl");
        mnMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnMatkulActionPerformed(evt);
            }
        });
        mnMaster.add(mnMatkul);
        mnMaster.add(jSeparator7);

        mnRuang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_R, java.awt.event.InputEvent.ALT_MASK));
        mnRuang.setText("Ruang");
        mnRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRuangActionPerformed(evt);
            }
        });
        mnMaster.add(mnRuang);
        mnMaster.add(jSeparator2);

        mnDtMatkul.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_K, java.awt.event.InputEvent.ALT_MASK));
        mnDtMatkul.setText("Detail Mata Kuliah");
        mnDtMatkul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDtMatkulActionPerformed(evt);
            }
        });
        mnMaster.add(mnDtMatkul);
        mnMaster.add(jSeparator4);

        mnDtRuang.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_G, java.awt.event.InputEvent.ALT_MASK));
        mnDtRuang.setText("Detail Ruang");
        mnDtRuang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDtRuangActionPerformed(evt);
            }
        });
        mnMaster.add(mnDtRuang);
        mnMaster.add(jSeparator5);

        mnJadwal.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.ALT_MASK));
        mnJadwal.setText("Jadwal");
        mnJadwal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJadwalActionPerformed(evt);
            }
        });
        mnMaster.add(mnJadwal);

        jMenuBar1.add(mnMaster);

        nmReservasi.setText("Reservasi");

        mnReservasi.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_WINDOWS, java.awt.event.InputEvent.ALT_MASK));
        mnReservasi.setText("Reservasi");
        mnReservasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnReservasiActionPerformed(evt);
            }
        });
        nmReservasi.add(mnReservasi);

        jMenuBar1.add(nmReservasi);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnDosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDosenActionPerformed
        // TODO add your handling code here:
        frmDosen fd=new frmDosen();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(fd);
        fd.setVisible(true);
    }//GEN-LAST:event_mnDosenActionPerformed

    private void mnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnExitActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_mnExitActionPerformed

    private void mnMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnMatkulActionPerformed
        // TODO add your handling code here:
        frmMatkul r=new frmMatkul();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_mnMatkulActionPerformed

    private void mnJadwalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJadwalActionPerformed
        // TODO add your handling code here:
        frmJadwal j=new frmJadwal();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(j);
        j.setVisible(true);
    }//GEN-LAST:event_mnJadwalActionPerformed

    private void mnRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRuangActionPerformed
        // TODO add your handling code here:
        frmRuang r=new frmRuang();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(r);
        r.setVisible(true);
    }//GEN-LAST:event_mnRuangActionPerformed

    private void mnReservasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnReservasiActionPerformed
        // TODO add your handling code here:
        frmPermintaan p=new frmPermintaan();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_mnReservasiActionPerformed

    private void mnDtMatkulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDtMatkulActionPerformed
        // TODO add your handling code here:
        frmDtMatkul p=new frmDtMatkul();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_mnDtMatkulActionPerformed

    private void mnDtRuangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDtRuangActionPerformed
        // TODO add your handling code here:
        frmDtRuang p=new frmDtRuang();
        dpHome.removeAll();
        dpHome.updateUI();
        dpHome.add(p);
        p.setVisible(true);
    }//GEN-LAST:event_mnDtRuangActionPerformed

    /**
     * @param args the command line arguments
     */
    @SuppressWarnings("unchecked")
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new frmUtama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane dpHome;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JPopupMenu.Separator jSeparator6;
    private javax.swing.JPopupMenu.Separator jSeparator7;
    private javax.swing.JLabel lblGambar;
    private javax.swing.JMenuItem mnDosen;
    private javax.swing.JMenuItem mnDtMatkul;
    private javax.swing.JMenuItem mnDtRuang;
    private javax.swing.JMenuItem mnExit;
    private javax.swing.JMenuItem mnJadwal;
    private javax.swing.JMenu mnMaster;
    private javax.swing.JMenuItem mnMatkul;
    private javax.swing.JMenu mnMenu;
    private javax.swing.JMenuItem mnReservasi;
    private javax.swing.JMenuItem mnRuang;
    private javax.swing.JMenu nmReservasi;
    // End of variables declaration//GEN-END:variables
}
